### ISSUE TITLE
'Nun of Ulric' is missing (i guess) 

### ISSUE THREAD

**Issue by LeRatierBretonnien** [hellogriffalo/Divine-Careers#1]
All in the title

BTW, i translated you're module into French, it will be included in the next release of the French Translation module for WFRP4E.

**Comment by hellogriffalo** [comment]
Hi there! Thanks for your feedback.

I have checked the compendium and Nun of Ulric is showing up - have you updated to the latest version?

**Comment by LeRatierBretonnien** [comment]
Yes, sorry, seems OK.
